### ISSUE TITLE
Quick Question, RE: iPhone X + iPhone 8 touch/face ID

### ISSUE THREAD

**Issue by MrBenFTW** [pwn20wndstuff/noncereboot1131UI#1]
Hello, I updated my blobs, and also added cool star's custom AP nonces, 
Does this mean that face/Touch ID is now fixed? IE if I use blobs will it break touch/Face ID?

**Comment by pwn20wndstuff** [comment]
My tool just sets the nonce. Ask those to the futurerestore guys.
