### ISSUE TITLE
Need help using the noncereboot + futurerestore

### ISSUE THREAD

**Issue by Alex2610** [pwn20wndstuff/noncereboot1131UI#13]
Hello, I have my own iPad air 2 on iOS 11.3 and I want to downgrade to iOS 11.0.1, I already have my shsh2 and generator string but where do I have to put the string and what I am supposed to press to set the generator and start the ./futurerestore thing?

**Comment by rnavalgund** [comment]
you cannot downgrade to 11.0.1 because there is no compatible SEP for it.
