### ISSUE TITLE
Downgrade from iOS 11.3 to 10.2? Noncereboot and Futurerestore

### ISSUE THREAD

**Issue by zachjonso** [pwn20wndstuff/noncereboot1131UI#16]
I have my shsh2 blobs saved from 10.2 but unwillingly updated to 11.3 a while ago overnight. I've heard the SEP is not compatible from iOS 11 down to 10, correct? I've attempted it with noncereboot and futurerestore but no luck.

**Comment by rnavalgund** [comment]
Please ask questions on twitter or r/Jailbreak discord, thanks.
